"""Read-only admin dashboard interpretation panels."""
from __future__ import annotations

from pathlib import Path

from backend.services.complete_synthetic_xai import (
    DEFAULT_XAI_PLOT_JSON_PATH,
    DEFAULT_XAI_PLOT_PATH,
    load_xai_global_importance,
)

# -- Domain gap analysis -------------------------------------------------------

def _domain_gap_analysis(breastdcedl_metrics):
    """
    Structured domain-gap analysis explaining why internal synthetic metrics do not
    constitute clinical validation. Keeps the weak external AUROC (~0.637) honest
    while providing a reusable framing for portfolio reviewers.
    """
    real_models = (breastdcedl_metrics or {}).get("models") or {}
    real_best_key = (breastdcedl_metrics or {}).get("best_model_by_roc_auc")
    real_best = real_models.get(real_best_key, {}) if real_best_key else {}
    real_auroc = real_best.get("roc_auc")

    return {
        "purpose": (
            "Explains the gap between internal synthetic metrics (AUROC ~0.99) and "
            "the exploratory real-data baseline (AUROC ~0.637). "
            "This framing is required before any claim of clinical utility."
        ),
        "internal_synthetic_auroc_note": (
            "The synthetic model achieves near-perfect AUROC because it was trained "
            "and tested on data generated by the same simulator. This measures "
            "simulator-learning fidelity, not real-world clinical discriminability."
        ),
        "real_data_external_auroc": real_auroc,
        "gap_dimensions": [
            {
                "dimension": "Feature mismatch",
                "description": (
                    "Synthetic features (WBC, ANC, platelets, MRI percent change) are "
                    "generated by a parametric simulator. Real EHR features have different "
                    "distributions, correlation structure, measurement noise, and missingness "
                    "patterns. Lab units, reference ranges, and timing conventions vary by site."
                ),
                "severity": "high",
            },
            {
                "dimension": "Label mismatch",
                "description": (
                    "treatment_success_binary is defined by the simulator's latent response "
                    "strength, not by a validated clinical pCR adjudication process. "
                    "Real pCR labels require pathology confirmation post-surgery. "
                    "The simulator label is a proxy, not a clinical ground truth."
                ),
                "severity": "high",
            },
            {
                "dimension": "Cohort mismatch",
                "description": (
                    "Synthetic patients are drawn from a parametric distribution. "
                    "Real cohorts (I-SPY1, BreastDCEDL) have site-specific enrollment "
                    "criteria, era-specific treatment protocols, and demographic biases "
                    "not captured by the simulator. Temporal drift between training and "
                    "deployment cohorts is not modelled."
                ),
                "severity": "high",
            },
            {
                "dimension": "Synthetic simulator bias",
                "description": (
                    "The simulator deterministically links latent_response_strength to "
                    "treatment_success_binary. A well-tuned ML model can learn this "
                    "deterministic mapping perfectly. Real clinical outcomes involve "
                    "unmeasured confounders, physician decisions, and biological variation "
                    "that no simulator fully captures."
                ),
                "severity": "critical",
            },
            {
                "dimension": "Temporal generalization",
                "description": (
                    "Models trained on earlier synthetic patient timelines may degrade "
                    "on later ones (tested via temporal_eval). In real deployments, "
                    "treatment guidelines, scanner hardware, and patient populations "
                    "evolve continuously. Periodic retraining and distribution monitoring "
                    "are required."
                ),
                "severity": "medium",
            },
            {
                "dimension": "Calibration gap",
                "description": (
                    "Probability calibration (ECE ~0.03-0.06) is evaluated on synthetic "
                    "holdout data only. Real-world probability reliability requires "
                    "external prospective validation before any patient-facing risk score "
                    "language is used."
                ),
                "severity": "medium",
            },
        ],
        "what_this_project_does_prove": [
            "End-to-end MLOps pipeline: data contract, training, calibration, holdout eval, drift monitoring.",
            "Agent safety: guardrail architecture, prompt injection blocking, clinical boundary enforcement.",
            "RAG credibility: hybrid dense+sparse retrieval with honest source attribution.",
            "MLE practices: versioned thresholds, leakage audit, temporal split, noise robustness.",
            "Exploratory real-data baseline: honest AUROC ~0.637 on MRI-derived tabular features.",
        ],
        "what_this_project_does_not_prove": [
            "Clinical safety or efficacy of any treatment recommendation.",
            "Real-world discriminability of pCR classification.",
            "Generalization to any specific hospital, scanner, or patient population.",
            "Calibrated probabilities reliable enough for clinical risk stratification.",
            "Equivalence of synthetic-data performance to prospective clinical trial performance.",
        ],
        "pathway_to_real_validation": [
            "1. Partner with a clinical institution for prospective data collection.",
            "2. Define pCR adjudication protocol with pathology confirmation.",
            "3. Run prospective pilot: model predictions logged, not acted upon.",
            "4. Evaluate with pre-registered analysis plan (AUROC, calibration, subgroups).",
            "5. Ethics review and IRB approval before any patient-facing deployment.",
        ],
        "honest_summary": (
            f"External exploratory AUROC on real MRI-derived features: "
            f"{round(real_auroc, 3) if real_auroc else 'not available'}. "
            "This gap (~0.36 AUROC points) between synthetic and real is the most "
            "important honesty signal in this project. Synthetic metrics demonstrate "
            "MLOps maturity; real-data metrics demonstrate the domain gap challenge."
        ),
    }


# -- Dashboard panels (XAI, confusion matrix, calibration, report links) -------

def _confusion_matrix_panel(advanced_eval):
    """Extract the locked-holdout confusion matrix at threshold 0.5 for the dashboard."""
    if not advanced_eval or advanced_eval.get("status") == "unavailable":
        return {"status": "unavailable", "message": "Run model training to generate predictions."}

    ops = advanced_eval.get("threshold_operating_points") or {}
    rows = ops.get("rows") or []
    at_50 = next((r for r in rows if r.get("threshold") == 0.5), None)
    if not at_50:
        return {"status": "unavailable", "message": "Threshold operating points not found."}

    tp = at_50.get("true_positive", 0)
    fp = at_50.get("false_positive", 0)
    fn = at_50.get("false_negative", 0)
    tn = at_50.get("true_negative", 0)
    total = tp + fp + fn + tn or 1
    return {
        "status": "available",
        "threshold": 0.5,
        "champion_model": advanced_eval.get("champion_model"),
        "matrix": {
            "true_positive": tp,
            "false_positive": fp,
            "false_negative": fn,
            "true_negative": tn,
            "total": total,
        },
        "rates": {
            "sensitivity": at_50.get("sensitivity"),
            "specificity": at_50.get("specificity"),
            "precision": at_50.get("precision"),
            "false_negative_rate": at_50.get("false_negative_rate"),
            "false_positive_rate": at_50.get("false_positive_rate"),
        },
        "display_hint": "2x2 confusion matrix at threshold=0.5 on locked holdout predictions.",
        "warning": "Synthetic data only - not clinical validation.",
    }


def _calibration_panel(advanced_eval):
    """Surface calibration bins and ECE for the dashboard reliability diagram."""
    if not advanced_eval or advanced_eval.get("status") == "unavailable":
        return {"status": "unavailable", "message": "Calibration data unavailable."}

    calibration = advanced_eval.get("calibration") or {}
    bins = calibration.get("bins") or []
    if not bins:
        return {"status": "unavailable", "message": "No calibration bins computed."}

    return {
        "status": calibration.get("status", "unavailable"),
        "expected_calibration_error": calibration.get("expected_calibration_error"),
        "brier_score": calibration.get("brier_score"),
        "bins": bins,
        "display_hint": (
            "Reliability diagram: each bin shows mean predicted probability vs observed positive rate. "
            "Perfect calibration = diagonal line."
        ),
        "recommendation": calibration.get("recommendation"),
        "warning": "Synthetic data only - not clinical validation.",
    }


def _feature_explanation_panel():
    """Load saved XAI global importance for the dashboard."""
    xai = load_xai_global_importance()
    if xai is None:
        return {
            "status": "unavailable",
            "message": (
                "Run generate_complete_synthetic_xai() to produce feature explanations. "
                "The plot and chart JSON will appear here."
            ),
        }

    top = (xai.get("global_importance") or [])[:15]
    return {
        "status": "available",
        "method": xai.get("method"),
        "method_label": xai.get("method_label"),
        "shap_available": xai.get("shap_available"),
        "plot_png_path": xai.get("plot_png_path"),
        "plot_chart_json_path": xai.get("plot_chart_json_path"),
        "top_features": top,
        "warning": xai.get("warning"),
        "display_hint": (
            "Bar chart of mean |contribution| per feature across all synthetic patients. "
            "Higher bar = larger average impact on model output direction."
        ),
    }


def _evaluation_report_links():
    """Return structured links to all evaluation artifacts so the dashboard can link them."""
    artifacts = [
        {
            "name": "Detailed training report",
            "path": "Data/model_evaluation_reports/latest_detailed_training_report.json",
            "description": "Per-model metrics, confusion matrices, training curves, and feature importances.",
        },
        {
            "name": "Locked holdout report",
            "path": "Data/complete_synthetic_training/locked_holdout/locked_holdout_manifest.json",
            "description": "Held-out evaluation on rows never seen during training.",
        },
        {
            "name": "External validation report",
            "path": "Data/model_evaluation_reports/latest_external_validation_report.json",
            "description": "BreastDCEDL / I-SPY1 domain-gap evaluation (AUROC ~0.637 - honest gap evidence).",
        },
        {
            "name": "Model comparison report",
            "path": "Data/model_evaluation_reports/latest_model_comparison_report.json",
            "description": "Side-by-side champion vs challenger comparison across metrics.",
        },
        {
            "name": "Temporal leakage audit",
            "path": "Data/complete_synthetic_training/leakage_audit/temporal_leakage_audit.json",
            "description": "Verifies no future-cycle data leaked into training rows.",
        },
        {
            "name": "Feature explanation JSON",
            "path": "Data/complete_synthetic_training/synthetic_xai_explanations.json",
            "description": "Per-patient and global feature contributions from the champion model.",
        },
        {
            "name": "Feature explanation plot (PNG)",
            "path": DEFAULT_XAI_PLOT_PATH,
            "description": "Global feature importance bar chart (matplotlib PNG).",
        },
        {
            "name": "Feature explanation chart data (JSON)",
            "path": DEFAULT_XAI_PLOT_JSON_PATH,
            "description": "Chart-data JSON for frontend rendering of the feature importance bar chart.",
        },
        {
            "name": "MLE readiness report",
            "path": "Data/mle_monitoring/latest_mle_readiness.json",
            "description": "End-to-end readiness gates: data contract, artifacts, performance, registry, audit.",
        },
        {
            "name": "Temporal generalization report",
            "path": "Data/mle_monitoring/temporal_eval_report.json",
            "description": "Earlier synthetic patient timelines vs later synthetic timelines.",
        },
        {
            "name": "High-noise robustness report",
            "path": "Data/mle_monitoring/noise_eval_report.json",
            "description": "CBC missingness, jitter, unit errors, site batch shift, and contradictory symptom stress test.",
        },
        {
            "name": "Calibration comparison report",
            "path": "Data/mle_monitoring/calibration_eval_report.json",
            "description": "Raw vs post-hoc calibrated probability reliability comparison.",
        },
    ]
    enriched = []
    for artifact in artifacts:
        exists = Path(artifact["path"]).exists()
        enriched.append({**artifact, "exists": exists})
    return {
        "purpose": "Links to all evaluation artifacts for dashboard navigation.",
        "artifacts": enriched,
    }
