from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from backend.services.oncology_canonical_schema import ROOT_DIR


DEFAULT_OUTPUT_PATH = "Data/evals/models/latest_data_promotion_roadmap.json"


ARTIFACTS = {
    "public_biomarker_readiness": "Data/evals/models/latest_public_biomarker_dataset_readiness.json",
    "public_treatment_readiness": "Data/evals/models/latest_public_treatment_dataset_readiness.json",
    "deep_learning_candidates": "Data/evals/models/latest_deep_learning_candidate_benchmark.json",
    "external_bridge": "Data/evals/models/latest_external_data_bridge_eval.json",
    "treatment_sequences": "Data/evals/models/latest_treatment_sequence_feature_eval.json",
    "shortcut_audit": "Data/evals/models/latest_shortcut_audit.json",
    "toxicity_feature_audit": "Data/evals/models/latest_toxicity_feature_audit.json",
    "subgroup_metrics": "Data/evals/models/latest_hybrid_subgroup_metrics.json",
    "per_head_calibration": "Data/evals/models/latest_per_head_calibration.json",
}

CLAIM_BOUNDARY = (
    "This roadmap is an engineering promotion plan under student-accessible constraints. It does not establish "
    "clinical validity, clinician sign-off, treatment efficacy, genetic-risk interpretation, or real patient prediction utility."
)


def build_data_promotion_roadmap(output_path: str | None = DEFAULT_OUTPUT_PATH) -> dict[str, Any]:
    artifacts = {name: _load_artifact(path) for name, path in ARTIFACTS.items()}
    heads = [
        _response_classification_plan(artifacts),
        _response_regression_plan(artifacts),
        _toxicity_signal_plan(artifacts),
        _genetic_biomarker_context_plan(artifacts),
        _tumor_marker_context_plan(artifacts),
        _treatment_sequence_context_plan(artifacts),
    ]
    blockers = _collect_blockers(heads)
    non_promotional_policies = {
        "monitor_only",
        "review_hint_only",
        "context_and_review_routing_only",
        "education_and_review_context_only",
        "timeline_context_only",
    }
    payload: dict[str, Any] = {
        "schema_version": "data_promotion_roadmap_v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "status": "strong" if all(head["current_policy"] in non_promotional_policies for head in heads) else "needs_attention",
        "artifact_inputs": {
            name: {
                "path": path,
                "exists": artifacts[name].get("_exists", False),
                "status": artifacts[name].get("status"),
            }
            for name, path in ARTIFACTS.items()
        },
        "summary": {
            "model_head_count": len(heads),
            "blocker_count": len(blockers),
            "current_global_policy": "monitor_only",
            "may_influence_treatment": False,
        },
        "model_heads": heads,
        "cross_head_blockers": blockers,
        "next_big_steps": _next_big_steps(),
        "promotion_policy": {
            "current_global_policy": "monitor_only",
            "may_show_to_patient": "only with non-diagnostic wording, evidence sufficiency, and clinician-review boundary",
            "may_influence_treatment": False,
            "minimum_future_evidence_for_any_promotion": [
                "clinician-reviewed labels for the exact task",
                "external temporal validation on data not generated by the simulator",
                "leakage audit passing on mapped external features",
                "calibration and subgroup reliability within prespecified thresholds",
                "failure-case review and documented mitigation",
                "clinical advisor review of language, thresholds, and workflow",
            ],
        },
        "claim_boundary": CLAIM_BOUNDARY,
    }
    if output_path:
        path = _resolve(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return payload


def _response_classification_plan(artifacts: dict[str, dict[str, Any]]) -> dict[str, Any]:
    external = artifacts["external_bridge"]
    dl = artifacts["deep_learning_candidates"]
    external_roles = _dig(external, ["coverage", "roles_supported"]) or {}
    return {
        "head": "response_classification",
        "current_policy": "monitor_only",
        "current_evidence": [
            "synthetic leakage-gated training and evaluation",
            "modality-aware abstention and robustness checks",
            "BreastDCEDL pCR/MRI bridge as external sanity-check only",
        ],
        "best_current_candidate": {
            "synthetic_deep_learning_auroc": _dig(dl, ["best_model", "classification_auroc"]),
            "external_breastdcedl_roc_auc": _dig(external, ["external_model_snapshot", "models", "logistic_regression", "roc_auc"]),
        },
        "not_ready_because": [
            "BreastDCEDL bridge supports pCR/MRI only, not the full OncoTrack timeline.",
            "No external CBC/symptom/medication-cycle response labels are mapped.",
            "Synthetic performance may reflect simulator structure.",
        ],
        "promotion_requirements": [
            "map at least one external cohort with response labels into canonical schema",
            "evaluate candidate and champion under identical feature subsets",
            "show calibrated performance and failure cases by subtype/stage",
        ],
        "external_roles_supported": external_roles,
    }


def _response_regression_plan(artifacts: dict[str, dict[str, Any]]) -> dict[str, Any]:
    shortcut = artifacts["shortcut_audit"]
    return {
        "head": "response_regression",
        "current_policy": "monitor_only",
        "current_evidence": [
            "synthetic response-score regression with uncertainty band",
            "shortcut audit documenting MRI percent-change dependence",
            "deep-learning regression candidate benchmark",
        ],
        "best_current_candidate": {
            "regression_model": _dig(artifacts["deep_learning_candidates"], ["best_models", "regression", "model"]),
            "regression_mae_percent": _dig(artifacts["deep_learning_candidates"], ["best_models", "regression", "regression_mae_percent"]),
        },
        "not_ready_because": [
            "response score is simulator-defined and partly tied to MRI percent-change",
            "external pCR is binary and not equivalent to the 0-100 synthetic response score",
        ],
        "promotion_requirements": [
            "define an external ordinal/continuous response endpoint",
            "calibrate interval coverage on external data",
            "separate imaging-supported signal from unsupported model extrapolation",
        ],
        "shortcut_status": shortcut.get("status"),
    }


def _toxicity_signal_plan(artifacts: dict[str, dict[str, Any]]) -> dict[str, Any]:
    toxicity_audit = artifacts["toxicity_feature_audit"]
    return {
        "head": "toxicity_signal",
        "current_policy": "review_hint_only",
        "current_evidence": [
            "synthetic toxicity classifier",
            "softer toxicity target benchmark",
            "feature audit documenting shortcut-prone legacy target",
        ],
        "not_ready_because": [
            "legacy toxicity target is heavily determined by simulator-generated nadir CBC fields",
            "no clinician-adjudicated toxicity labels are available",
        ],
        "promotion_requirements": [
            "redesign toxicity target as review-priority label, not diagnosis",
            "validate against clinician-reviewed adverse-event or triage labels",
            "calibrate by CBC missingness and symptom-only cases",
        ],
        "audit_status": toxicity_audit.get("status"),
    }


def _genetic_biomarker_context_plan(artifacts: dict[str, dict[str, Any]]) -> dict[str, Any]:
    readiness = artifacts["public_biomarker_readiness"]
    return {
        "head": "genetic_biomarker_context",
        "current_policy": "context_and_review_routing_only",
        "current_evidence": [
            "public biomarker dataset readiness map",
            "synthetic genetic context ablation",
            "canonical schema fields for ER/PR/HER2/Ki-67 and variant classification",
        ],
        "not_ready_because": [
            "genetic features in synthetic rows are simulated context, not real genetic-test records",
            "genetic information should not be treated as direct treatment-response proof",
        ],
        "promotion_requirements": [
            "map real biomarker/genomic cohort fields with permitted use",
            "separate germline, somatic, biomarker, and family-history roles",
            "keep VUS and hereditary-risk outputs routed to counselor/clinician review",
        ],
        "candidate_training_recommended": _dig(readiness, ["retraining_decision", "candidate_training_recommended"]),
    }


def _tumor_marker_context_plan(artifacts: dict[str, dict[str, Any]]) -> dict[str, Any]:
    readiness = artifacts["public_biomarker_readiness"]
    return {
        "head": "tumor_marker_context",
        "current_policy": "education_and_review_context_only",
        "current_evidence": [
            "tumor-marker source mapping",
            "claim-boundary and overclaim refusal tests",
        ],
        "not_ready_because": [
            "no longitudinal serum tumor-marker response cohort is mapped",
            "CA 15-3, CA 27.29, and CEA cannot stand alone as response or recurrence proof",
        ],
        "promotion_requirements": [
            "find or obtain longitudinal tumor-marker plus imaging/outcome data",
            "evaluate markers as weak contextual trend features only",
            "prespecify overclaim tests and clinician-review routing",
        ],
        "tumor_marker_response_train_ready": _dig(readiness, ["summary", "tumor_marker_response_train_ready"]),
    }


def _treatment_sequence_context_plan(artifacts: dict[str, dict[str, Any]]) -> dict[str, Any]:
    treatment_readiness = artifacts["public_treatment_readiness"]
    sequences = artifacts["treatment_sequences"]
    return {
        "head": "treatment_sequence_context",
        "current_policy": "timeline_context_only",
        "current_evidence": [
            "synthetic treatment-sequence artifact",
            "public treatment-combination dataset readiness map",
            "deep-learning treatment-context ablation",
        ],
        "not_ready_because": [
            "synthetic treatment combinations are simulator context",
            "no local real-world regimen-by-cycle dataset with outcomes is available",
        ],
        "promotion_requirements": [
            "map treatment modalities from external cohort into canonical schema",
            "run A/B comparisons with and without treatment-sequence features",
            "prove features improve calibration without recommending treatment",
        ],
        "synthetic_pattern_count": sequences.get("pattern_count"),
        "immediate_full_treatment_combo_training_ready": _dig(
            treatment_readiness,
            ["summary", "immediate_full_treatment_combo_training_ready"],
        ),
        "best_future_real_world_treatment_dataset": _dig(
            treatment_readiness,
            ["summary", "best_future_real_world_treatment_dataset"],
        ),
    }


def _collect_blockers(heads: list[dict[str, Any]]) -> list[str]:
    blockers: list[str] = []
    for head in heads:
        blockers.extend(f"{head['head']}: {reason}" for reason in head.get("not_ready_because", []))
    return blockers


def _next_big_steps() -> list[dict[str, Any]]:
    return [
        {
            "rank": 1,
            "step": "Map one more public external cohort into the canonical schema",
            "why": "BreastDCEDL is useful but narrow; a second external cohort reduces single-dataset tunnel vision.",
            "student_feasible_now": True,
            "suggested_target": "TCGA-BRCA or METABRIC schema/distribution mapping via public APIs",
        },
        {
            "rank": 2,
            "step": "Run strict feature-subset A/B tests",
            "why": "Compare synthetic champion, deep-learning candidate, and external pCR baseline on common fields only.",
            "student_feasible_now": True,
            "suggested_target": "age + subtype + imaging features where available",
        },
        {
            "rank": 3,
            "step": "Improve toxicity labels from tautology to review-priority simulator target",
            "why": "The current toxicity signal is useful as a review hint but too tied to generated nadir CBC.",
            "student_feasible_now": True,
            "suggested_target": "multi-factor label using symptoms, CBC trajectory, intervention, and missingness noise",
        },
        {
            "rank": 4,
            "step": "Build an external failure-case review table",
            "why": "Reviewers trust projects more when external errors are visible and categorized.",
            "student_feasible_now": True,
            "suggested_target": "false positives/false negatives by subtype and confidence bucket",
        },
        {
            "rank": 5,
            "step": "Prepare data-access packet for future restricted cohorts",
            "why": "GENIE BPC and SEER-Medicare are promising but require access steps.",
            "student_feasible_now": True,
            "suggested_target": "fields requested, use case, non-diagnostic analysis plan, privacy boundary",
        },
    ]


def _load_artifact(path: str) -> dict[str, Any]:
    resolved = _resolve(path)
    if not resolved.exists():
        return {"_exists": False}
    try:
        payload = json.loads(resolved.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        return {"_exists": True, "_error": str(exc)}
    if isinstance(payload, dict):
        payload["_exists"] = True
        return payload
    return {"_exists": True, "_error": "artifact is not a JSON object"}


def _resolve(path: str | Path) -> Path:
    candidate = Path(path)
    return candidate if candidate.is_absolute() else ROOT_DIR / candidate


def _dig(payload: dict[str, Any], path: list[str]) -> Any:
    value: Any = payload
    for key in path:
        if not isinstance(value, dict):
            return None
        value = value.get(key)
    return value
