import { Sparkles, CheckCircle, AlertTriangle, Info } from "lucide-react";
import { SectionCard } from "../../components/ui/SectionCard";
import type { AiSummary } from "../../types/api";

function toArray(v: string | string[] | undefined): string[] {
  if (!v) return [];
  return Array.isArray(v) ? v : [v];
}

interface Props { summary: AiSummary | null }

function SummaryColumn({
  icon: Icon,
  title,
  tone,
  items,
  empty,
}: {
  icon: typeof CheckCircle;
  title: string;
  tone: "success" | "warning";
  items: string[];
  empty: string;
}) {
  const palette =
    tone === "success"
      ? { bg: "#f0fdf4", border: "#bbf7d0", fg: "#047857", chip: "#dcfce7" }
      : { bg: "#fffbeb", border: "#fde68a", fg: "#92400e", chip: "#fef3c7" };
  return (
    <div
      className="rounded-lg border p-3.5 flex flex-col gap-2"
      style={{ background: palette.bg, borderColor: palette.border }}
    >
      <div className="flex items-center gap-2">
        <span
          className="inline-flex items-center justify-center"
          style={{
            width: 22, height: 22,
            borderRadius: 6,
            background: palette.chip,
            color: palette.fg,
            flexShrink: 0,
          }}
        >
          <Icon size={12} />
        </span>
        <span
          className="text-[0.74rem] font-semibold uppercase tracking-wide"
          style={{ color: palette.fg }}
        >
          {title}
        </span>
      </div>
      {items.length > 0 ? (
        <ul className="flex flex-col gap-1.5 pl-0.5">
          {items.map((s, i) => (
            <li
              key={i}
              className="text-[0.82rem] leading-relaxed"
              style={{ color: "var(--text)" }}
            >
              {s}
            </li>
          ))}
        </ul>
      ) : (
        <p className="text-[0.78rem]" style={{ color: "var(--text-dim)" }}>{empty}</p>
      )}
    </div>
  );
}

export function AiSummaryPanel({ summary }: Props) {
  if (!summary) return null;
  const explanation = toArray(summary.patient_explanation);
  const reasons = summary.review_reasons ?? [];

  return (
    <SectionCard
      title="AI snapshot"
      icon={Sparkles}
      meta="updated just now"
      footer={
        <span className="inline-flex items-center gap-1.5">
          <Info size={11} aria-hidden="true" />
          Generated by an AI assistant using your records. Not a clinical diagnosis — discuss with your oncology team.
        </span>
      }
    >
      <div className="grid gap-3 md:grid-cols-2">
        <SummaryColumn
          icon={CheckCircle}
          title="Key signals"
          tone="success"
          items={explanation}
          empty="No summary available yet."
        />
        <SummaryColumn
          icon={AlertTriangle}
          title="Review with care team"
          tone="warning"
          items={reasons}
          empty="Nothing flagged today."
        />
      </div>
    </SectionCard>
  );
}
