import { Brain, AlertTriangle, CheckCircle, HelpCircle } from "lucide-react";
import { Card, CardHeader, SectionTitle } from "../../components/ui/Card";
import type { AiSummary } from "../../types/api";

function toArray(v: string | string[] | undefined): string[] {
  if (!v) return [];
  return Array.isArray(v) ? v : [v];
}

interface Props { summary: AiSummary | null }

export function AiSummaryPanel({ summary }: Props) {
  if (!summary) return null;
  const explanation = toArray(summary.patient_explanation);
  const reasons = summary.review_reasons ?? [];

  return (
    <Card>
      <CardHeader>
        <SectionTitle>AI Snapshot</SectionTitle>
        <Brain size={14} style={{ color: "var(--text-faint)" }} />
      </CardHeader>

      <div className="grid gap-3 sm:grid-cols-3">
        {/* Patient explanation */}
        <div
          className="rounded-md p-3 flex flex-col gap-1.5 border"
          style={{ background: "rgba(16,185,129,0.05)", borderColor: "rgba(16,185,129,0.18)" }}
        >
          <div className="flex items-center gap-1.5">
            <CheckCircle size={13} style={{ color: "var(--green)" }} />
            <span className="text-xs font-semibold" style={{ color: "var(--green)" }}>Key signals</span>
          </div>
          {explanation.length > 0 ? (
            <ul className="list-none flex flex-col gap-1">
              {explanation.map((s, i) => (
                <li key={i} className="text-xs" style={{ color: "var(--text-dim)" }}>{s}</li>
              ))}
            </ul>
          ) : (
            <p className="text-xs" style={{ color: "var(--text-faint)" }}>No summary available</p>
          )}
        </div>

        {/* Review reasons */}
        <div
          className="rounded-md p-3 flex flex-col gap-1.5 border"
          style={{ background: "rgba(245,158,11,0.05)", borderColor: "rgba(245,158,11,0.18)" }}
        >
          <div className="flex items-center gap-1.5">
            <AlertTriangle size={13} style={{ color: "var(--amber)" }} />
            <span className="text-xs font-semibold" style={{ color: "var(--amber)" }}>Review with care team</span>
          </div>
          {reasons.length > 0 ? (
            <ul className="list-none flex flex-col gap-1">
              {reasons.map((r, i) => (
                <li key={i} className="text-xs" style={{ color: "var(--text-dim)" }}>{r}</li>
              ))}
            </ul>
          ) : (
            <p className="text-xs" style={{ color: "var(--text-faint)" }}>Nothing flagged</p>
          )}
        </div>

        {/* Disclaimer column */}
        <div
          className="rounded-md p-3 flex flex-col gap-1.5 border"
          style={{ background: "rgba(148,163,184,0.05)", borderColor: "var(--border)" }}
        >
          <div className="flex items-center gap-1.5">
            <HelpCircle size={13} style={{ color: "var(--text-dim)" }} />
            <span className="text-xs font-semibold" style={{ color: "var(--text-dim)" }}>About this summary</span>
          </div>
          <p className="text-xs" style={{ color: "var(--text-faint)" }}>
            Generated by an AI assistant using your records. Not a clinical diagnosis. Discuss any concerns with your oncology team.
          </p>
        </div>
      </div>
    </Card>
  );
}
