"""Build the machine-readable summary emitted by fresh-clone verification.

The inputs are generated by pytest/Vitest in the current run. This script does
not execute tests, infer success from timestamps, or write repository evidence;
it only consolidates ephemeral CI results under ``Data/test_tmp``.
"""

from __future__ import annotations

import argparse
import json
import platform
import subprocess
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def _read_json(path: Path) -> dict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return payload


def _git_sha() -> str:
    return subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def _node_version() -> str:
    return subprocess.run(
        ["node", "--version"], check=True, capture_output=True, text=True
    ).stdout.strip()


def build_summary(backend_report: Path, frontend_report: Path, coverage_report: Path) -> dict:
    backend = _read_json(backend_report)
    frontend = _read_json(frontend_report)
    coverage = _read_json(coverage_report)
    detail = backend.get("full_suite_detail") or {}
    frontend_total = coverage.get("total") or {}

    summary = {
        "schema_version": "fresh_clone_summary_v1",
        "commit_sha": _git_sha(),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "python_version": platform.python_version(),
        "node_version": _node_version(),
        "offline_mode": "NLCARE_TEST_OFFLINE=true",
        "backend": {
            "passed": bool(backend.get("passed")),
            "tests_collected": int(detail.get("tests_collected") or 0),
            "tests_passed": int(detail.get("passed") or 0),
            "tests_failed": int(detail.get("failed") or 0),
            "coverage_percent": detail.get("coverage_percent"),
            "coverage_floor": detail.get("coverage_floor"),
            "network_or_credential_skips": detail.get("network_or_credential_skips") or [],
        },
        "frontend": {
            "tests_total": int(frontend.get("numTotalTests") or 0),
            "tests_passed": int(frontend.get("numPassedTests") or 0),
            "tests_failed": int(frontend.get("numFailedTests") or 0),
            "coverage": {
                key: (frontend_total.get(key) or {}).get("pct")
                for key in ("statements", "branches", "functions", "lines")
            },
        },
        "gates": {
            "backend_lint": "passed",
            "backend_typecheck": "passed",
            "dependency_contract": "passed",
            "size_ratchet": "passed",
            "frontend_lint": "passed",
            "frontend_typecheck": "passed",
            "frontend_build": "passed",
            "network_block": "passed",
        },
        "claim_boundary": (
            "Engineering verification only. This summary is generated from the current "
            "clean-checkout run and does not alter clinical, DEP-001, RAG, or ML evidence."
        ),
    }
    if not summary["backend"]["passed"]:
        raise ValueError("backend report is not passing")
    if summary["backend"]["tests_collected"] <= 0 or summary["frontend"]["tests_total"] <= 0:
        raise ValueError("test counts must be positive")
    if summary["frontend"]["tests_failed"]:
        raise ValueError("frontend report contains failed tests")
    if summary["backend"]["network_or_credential_skips"]:
        raise ValueError("backend report contains network/credential skips")
    return summary


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--backend-report", type=Path, required=True)
    parser.add_argument("--frontend-report", type=Path, required=True)
    parser.add_argument("--coverage-report", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    payload = build_summary(args.backend_report, args.frontend_report, args.coverage_report)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
