import { ShieldAlert } from "lucide-react";

/**
 * EvalIntegrityFooter
 *
 * Compact, opinionated metadata strip designed to live at the bottom of an
 * admin eval card.  It surfaces the credibility signals a reviewer needs to
 * trust the metric above it without scrolling into the raw artifact:
 *
 *   - total_n / pass / fail / skipped
 *   - internal vs external author
 *   - clinical_validation (forced false here — every eval in this PoC is
 *     engineering-grade synthetic and must say so out loud)
 *   - was_used_for_tuning  (red flag if true on a holdout)
 *   - status (passed / acceptable / needs_attention / failed)
 *   - artifact path
 *   - claim boundary / caveat
 *
 * The component intentionally renders even when the eval's status is
 * "needs_attention" — visually that gets a warning tone, NOT a failure tone,
 * because the release gate accepts needs_attention as a soft warning.
 */
export type EvalIntegrityStatus =
  | "passed"
  | "acceptable"
  | "needs_attention"
  | "failed"
  | "skipped"
  | "missing"
  | "unknown";

export interface EvalIntegrityProps {
  totalN: number | null | undefined;
  passCount?: number | null;
  failCount?: number | null;
  skippedCount?: number | null;
  /** "internal" if authored by the project's eval team; "external" if generated by an outside dataset/source. */
  authorship: "internal" | "external" | "mixed";
  clinicalValidation: false;              // engineering-only PoC; always literal false
  wasUsedForTuning: boolean;               // true if model was tuned against this set — flag loudly
  status: EvalIntegrityStatus;
  artifactPath?: string | null;
  /** Short, plain-English claim boundary / caveat that travels with the eval. */
  caveat: string;
}

function statusTone(status: EvalIntegrityStatus): "good" | "warn" | "bad" | "muted" {
  switch (status) {
    case "passed":
    case "acceptable":
      return "good";
    case "needs_attention":
      return "warn";
    case "failed":
      return "bad";
    default:
      return "muted";
  }
}

function statusLabel(status: EvalIntegrityStatus): string {
  switch (status) {
    case "needs_attention": return "needs attention";
    default: return status;
  }
}

function fmtCount(value: number | null | undefined): string {
  if (value == null) return "—";
  return new Intl.NumberFormat("en-US").format(value);
}

export function EvalIntegrityFooter(props: EvalIntegrityProps) {
  const tone = statusTone(props.status);
  const statusClass =
    tone === "good"  ? "eval-integrity-value--good" :
    tone === "warn"  ? "eval-integrity-value--warn" :
    tone === "bad"   ? "eval-integrity-value--bad"  :
    "eval-integrity-value--muted";
  return (
    <div className="eval-integrity" data-eval-integrity>
      <div className="eval-integrity-grid" role="list" aria-label="Eval integrity metadata">
        <Cell label="Total n"   value={fmtCount(props.totalN)} />
        <Cell label="Passed"    value={fmtCount(props.passCount)} tone={props.passCount != null && props.passCount > 0 ? "good" : "muted"} />
        <Cell label="Failed"    value={fmtCount(props.failCount)} tone={props.failCount != null && props.failCount > 0 ? "bad" : "muted"} />
        <Cell label="Skipped"   value={fmtCount(props.skippedCount)} tone="muted" />
        <Cell label="Author"    value={props.authorship} tone="muted" />
        <Cell label="Clinical validation" value="false" tone="warn" />
        <Cell
          label="Used for tuning"
          value={props.wasUsedForTuning ? "true" : "false"}
          tone={props.wasUsedForTuning ? "bad" : "good"}
        />
        <Cell label="Status" value={statusLabel(props.status)} className={statusClass} />
      </div>
      {props.artifactPath && (
        <div className="eval-integrity-row">
          <span>Artifact:</span>
          <code>{props.artifactPath}</code>
        </div>
      )}
      <div className="eval-integrity-row">
        <ShieldAlert size={12} aria-hidden="true" style={{ marginTop: 2, flexShrink: 0 }} />
        <span>{props.caveat}</span>
      </div>
    </div>
  );
}

function Cell({
  label,
  value,
  tone,
  className,
}: {
  label: string;
  value: string;
  tone?: "good" | "warn" | "bad" | "muted";
  className?: string;
}) {
  const valueClass =
    className ??
    (tone === "good" ? "eval-integrity-value eval-integrity-value--good" :
     tone === "warn" ? "eval-integrity-value eval-integrity-value--warn" :
     tone === "bad"  ? "eval-integrity-value eval-integrity-value--bad"  :
     tone === "muted" ? "eval-integrity-value eval-integrity-value--muted" :
     "eval-integrity-value");
  return (
    <div className="eval-integrity-cell" role="listitem">
      <span className="eval-integrity-key">{label}</span>
      <span className={valueClass.startsWith("eval-integrity-value") ? valueClass : `eval-integrity-value ${valueClass}`}>
        {value}
      </span>
    </div>
  );
}
